quarkus.http.port=8081

#----------------- datasource -----------------#
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=dbUsername
quarkus.datasource.password=dbPassword
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//127.0.0.1:1521/CORE
quarkus.hibernate-orm.schema-management.strategy=update


quarkus.http.non-application-root-path=q
